### ISSUE TITLE
[Off-Platform Suggestion] Uncivilise

### ISSUE THREAD

**Issue by XargsUK** [XargsUK/awesome-adhd#5]
## Username of Suggestor
[Uncivilise](https://www.reddit.com/user/Uncivilise/)

## Link to Suggestion
https://www.reddit.com/r/ADHDUK/comments/13sm8xe/comment/jlszf77/?utm_source=share&utm_medium=web2x&context=3

## Suggestion
https://neurodivergentinsights.com/ - especially their 'misdiagnosis Monday'.

Also I often point people to the ASRS, available at Psychology Tools, which also had the VADRS: https://psychology-tools.com/

**Comment by LabyrinthMind-ADHD** [comment]
We already have this resource listed on the FAQ (Misdiagnosis Monday), and we don't tend to link the diagnostic scales directly as that could be seen as us trying to help people obtain a diagnosis. We do, however, go into detail about what they are in the FAQ.
