### ISSUE TITLE
[Section] watchOS

### ISSUE THREAD

**Issue by XargsUK** [XargsUK/awesome-adhd#7]
## Detailed Description

Apps are currently across phone and PC OSes, yet there's a large number of apps which are watch specific which I personally find extremely useful. We've already seen users recommended some watchOS specific apps. 

#### Pros

- Easier for users to find watch specific applications

#### Cons

- Another section adds to the complexity of the repo
- Duplication of resources across the phone application section and watch application section. 

#### Pros 

- Does not add another section
- Avoids duplication of resources

#### Cons 

- Doesn't handle cases where an app may be watch only 
- Another icon to the legend. 

Need to have a think about how to implement this.

**Comment by LabyrinthMind-ADHD** [comment]
I think that the watch situation is probably more of a niche case, so until you received more watch specific requests, it would make the most sense to add the Watch Icon instead of a brand-new section, then edit it later if you started getting more requests for that type of resource.
